export const fallbackQuestions = [
    "What's your favorite hobby?",
    "If you could travel anywhere, where would you go?",
    "What's a skill you'd like to learn?",
    "Do you prefer cats or dogs?",
    "What's your favorite book?",
    "What's a fun fact about yourself?",
    "If you could meet any famous person, who would it be?",
    "What's the best advice you've ever received?",
    "What would you do if you won the lottery?",
    "What's your favorite food?",
    "If you could have any superpower, what would it be?",
    "What's your dream job?",
    "What are you most passionate about?",
    "What's your favorite movie?",
    "Do you prefer the beach or the mountains?",
    "What's your favorite season of the year?",
    "If you could time travel, would you go to the past or future?",
    "What's one thing you'd change about the world?",
    "What's your biggest goal right now?",
    "What's something that always makes you smile?",
    "Sorry, I can't talk at this time, isn't that funny ? 😅",
        "Could you elaborate more on that? It sounds interesting!",
        "That reminds me, have you ever thought about trying something new recently?",
        "What’s the most exciting thing you’ve learned this week?",
        "You mentioned something intriguing earlier. Can you expand on that?",
        "If you could change one thing about today, what would it be?",
        "That’s a great point! What’s another example of that in your life?",
        "I was curious, what motivates you the most when you’re feeling unmotivated?",
        "That’s fascinating! How do you think others would view that?",
        "Has there been a moment that made you see things from a different perspective?",
        "You made a good point earlier! How would you approach it differently next time?",
        "What do you think is the most important factor in achieving success?",
        "I’d love to hear your thoughts on what inspires you daily!",
        "How do you usually respond when faced with tough challenges?",
        "That’s an interesting view! Have you had any experiences that changed your mind about it?",
        "Speaking of that, what’s one thing you feel like you’ve mastered recently?",
        "Do you think your goals have evolved over time? If so, how?",
        "What’s a skill you’ve learned that surprised you with how useful it became?",
        "I’m curious, do you prefer to work alone or with others, and why?",
        "If you were to give advice to your past self, what would it be?",
        "How do you handle situations where you’re outside of your comfort zone?",
        "What do you think has been your biggest accomplishment so far?",
        "How do you keep yourself focused when distractions come your way?",
        "Is there a particular moment in your life that shaped who you are today?",
        "That’s interesting! What drives your passion for that?",
        "What do you think people misunderstand about you the most?",
        "If you had a chance to start over, what would you do differently?",
        "How do you typically unwind after a long day?",
        "What’s something you’re currently working towards?",
        "What’s one challenge that has shaped your perspective?",
        "What’s the biggest lesson you’ve learned recently?",
        "If you had unlimited time, what would you dive deeper into?",
        "How do you stay motivated during tough times?",
        "What’s something you’re grateful for right now?",
        "Do you think your priorities have changed over the years? How so?",
        "What’s a goal you’ve achieved that made you really proud?",
        "How do you find balance in your daily life?",
        "What’s something you want to improve about yourself?",
        "How do you handle failure or setbacks in your life?",
        "What’s a dream you have yet to achieve?",
        "What do you do when you need inspiration?"
      ]